export const mockBoardData = [
  {
    id: "1",
    title: "To Do",
    bgColor: "bg-gray-200",
    textColor: "text-gray-800",
    tasks: [
      {
        label: "Research",
        labelColor: "green",
        title: "User interview",
        members: ["/images/icons/user_profile.svg"],
        dueDate: "Tomorrow",
        priority: "low",
        shareCount: 2,
        messageCount: 2,
        footerType: "due",
      },
      {
        label: "Design",
        labelColor: "red",
        title: "Design System",
        members: [
          "/images/icons/user_profile.svg",
          "/images/icons/user_profile.svg",
        ],
        dueDate: "",
        priority: "medium",
        shareCount: 3,
        messageCount: 8,
        footerType: "reports",
        reports: 2,
      },
      {
        label: "Other",
        labelColor: "gray",
        title: "Speech",
        members: [
          "/images/icons/user_profile.svg",
          "/images/icons/user_profile.svg",
          "/images/icons/user_profile.svg",
          "/images/icons/user_profile.svg",
        ],
        dueDate: "",
        priority: "low",
        shareCount: 1,
        messageCount: 3,
        footerType: "stream",
      },
      {
        label: "Design",
        labelColor: "blue",
        title: "Wireframe",
        members: [
          "/images/icons/user_profile.svg",
          "/images/icons/user_profile.svg",
          "/images/icons/user_profile.svg",
          "/images/icons/user_profile.svg",
        ],
        dueDate: "",
        priority: "high",
        imageUrl: "/images/image_placeholder.svg",
        footerType: "stream",
      },
    ],
  },
  {
    id: "2",
    title: "In Progress",
    bgColor: "bg-orange-400",
    textColor: "text-black",
    tasks: [
      {
        label: "Design",
        labelColor: "red",
        title: "UI Design",
        members: ["/images/icons/user_profile.svg"],
        dueDate: "Tomorrow",
        priority: "high",
        shareCount: 2,
        messageCount: 2,
        footerType: "due",
      },
      {
        label: "Feedback",
        labelColor: "blue",
        title: "Check Clients Feedback",
        members: [
          "/images/icons/user_profile.svg",
          "/images/icons/user_profile.svg",
          "/images/icons/user_profile.svg",
          "/images/icons/user_profile.svg",
        ],
        dueDate: "22 April, 2022",
        priority: "low",
        imageUrl: "/images/image_placeholder.svg",
        footerType: "due",
      },
      {
        label: "Presentation",
        labelColor: "orange",
        title: "Copyright",
        members: ["/images/icons/user_profile.svg"],
        dueDate: "22 April, 2022",
        priority: "low",
        shareCount: 4,
        messageCount: 0,
        footerType: "due",
      },
      {
        label: "UX Research",
        labelColor: "yellow",
        title: "Filter sorting",
        members: ["/images/icons/user_profile.svg"],
        dueDate: "",
        priority: "low",
        footerType: "none",
      },
    ],
  },
  {
    id: "3",
    title: "Approved",
    bgColor: "bg-lime-400",
    textColor: "text-black",
    tasks: [
      {
        label: "Research",
        labelColor: "green",
        title: "Prototype",
        members: [
          "/images/icons/user_profile.svg",
          "/images/icons/user_profile.svg",
          "/images/icons/user_profile.svg",
          "/images/icons/user_profile.svg",
        ],
        dueDate: "",
        priority: "low",
        shareCount: 35,
        messageCount: 243,
        footerType: "none",
      },
      {
        label: "Design",
        labelColor: "red",
        title: "Detail Page",
        dueDate: "22 April, 2025",
        members: [
          "/images/icons/user_profile.svg",
          "/images/icons/user_profile.svg",
          "/images/icons/user_profile.svg",
          "/images/icons/user_profile.svg",
        ],
        imageUrl: "/images/image_placeholder.svg",
        priority: "low",
        footerType: "due",
        shareCount: 6,
        messageCount: 28,
      },
    ],
  },
  {
    id: "4",
    title: "Reject",
    bgColor: "bg-red-500",
    textColor: "text-white",
    tasks: [
      {
        label: "Other",
        labelColor: "gray",
        title: "Group Management",
        members: ["/images/icons/user_profile.svg"],
        priority: "low",
        footerType: "link",
        linkLabel: "Group Call",
        shareCount: 329,
      },
      {
        label: "Design",
        labelColor: "red",
        title: "Design System",
        members: [
          "/images/icons/user_profile.svg",
          "/images/icons/user_profile.svg",
        ],
        priority: "low",
        footerType: "reports",
        reports: 2,
        shareCount: 3,
        messageCount: 8,
      },
      {
        label: "Interface",
        labelColor: "gray",
        title: "Slider controls",
        members: [
          "/images/icons/user_profile.svg",
          "/images/icons/user_profile.svg",
        ],
        priority: "low",
        shareCount: 8,
        messageCount: 31,
        footerType: "none",
      },
      {
        label: "Design",
        labelColor: "blue",
        title: "Slider controls",
        members: [
          "/images/icons/user_profile.svg",
          "/images/icons/user_profile.svg",
        ],
        priority: "low",
        shareCount: 8,
        messageCount: 31,
        footerType: "none",
      },
    ],
  },
  //   {
  //     id: "5",
  //     title: "Done",
  //     bgColor: "bg-lime-400",
  //     textColor: "text-black",
  //     tasks: [
  //       {
  //         label: "Research",
  //         labelColor: "green",
  //         title: "Prototype",
  //         members: [
  //           "/images/icons/user_profile.svg",
  //           "/images/icons/user_profile.svg",
  //           "/images/icons/user_profile.svg",
  //           "/images/icons/user_profile.svg",
  //         ],
  //         dueDate: "",
  //         priority: "low",
  //         shareCount: 35,
  //         messageCount: 243,
  //         footerType: "none",
  //       },
  //       {
  //         label: "Design",
  //         labelColor: "red",
  //         title: "Detail Page",
  //         dueDate: "22 April, 2025",
  //         members: [
  //           "/images/icons/user_profile.svg",
  //           "/images/icons/user_profile.svg",
  //           "/images/icons/user_profile.svg",
  //           "/images/icons/user_profile.svg",
  //         ],
  //         imageUrl: "/images/image_placeholder.svg",
  //         priority: "low",
  //         footerType: "due",
  //         shareCount: 6,
  //         messageCount: 28,
  //       },
  //     ],
  //   },
];
